spring.application.name=agencia-virtual-backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost/agencia_virtual}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false